// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mande/voting/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetVoteBookRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetVoteBookRequest) Reset()         { *m = QueryGetVoteBookRequest{} }
func (m *QueryGetVoteBookRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVoteBookRequest) ProtoMessage()    {}
func (*QueryGetVoteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{2}
}
func (m *QueryGetVoteBookRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVoteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVoteBookRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVoteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVoteBookRequest.Merge(m, src)
}
func (m *QueryGetVoteBookRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVoteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVoteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVoteBookRequest proto.InternalMessageInfo

func (m *QueryGetVoteBookRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetVoteBookResponse struct {
	VoteBook VoteBook `protobuf:"bytes,1,opt,name=voteBook,proto3" json:"voteBook"`
}

func (m *QueryGetVoteBookResponse) Reset()         { *m = QueryGetVoteBookResponse{} }
func (m *QueryGetVoteBookResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVoteBookResponse) ProtoMessage()    {}
func (*QueryGetVoteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{3}
}
func (m *QueryGetVoteBookResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVoteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVoteBookResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVoteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVoteBookResponse.Merge(m, src)
}
func (m *QueryGetVoteBookResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVoteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVoteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVoteBookResponse proto.InternalMessageInfo

func (m *QueryGetVoteBookResponse) GetVoteBook() VoteBook {
	if m != nil {
		return m.VoteBook
	}
	return VoteBook{}
}

type QueryAllVoteBookRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVoteBookRequest) Reset()         { *m = QueryAllVoteBookRequest{} }
func (m *QueryAllVoteBookRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllVoteBookRequest) ProtoMessage()    {}
func (*QueryAllVoteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{4}
}
func (m *QueryAllVoteBookRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVoteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVoteBookRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVoteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVoteBookRequest.Merge(m, src)
}
func (m *QueryAllVoteBookRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVoteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVoteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVoteBookRequest proto.InternalMessageInfo

func (m *QueryAllVoteBookRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllVoteBookResponse struct {
	VoteBook   []VoteBook          `protobuf:"bytes,1,rep,name=voteBook,proto3" json:"voteBook"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVoteBookResponse) Reset()         { *m = QueryAllVoteBookResponse{} }
func (m *QueryAllVoteBookResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllVoteBookResponse) ProtoMessage()    {}
func (*QueryAllVoteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{5}
}
func (m *QueryAllVoteBookResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVoteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVoteBookResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVoteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVoteBookResponse.Merge(m, src)
}
func (m *QueryAllVoteBookResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVoteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVoteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVoteBookResponse proto.InternalMessageInfo

func (m *QueryAllVoteBookResponse) GetVoteBook() []VoteBook {
	if m != nil {
		return m.VoteBook
	}
	return nil
}

func (m *QueryAllVoteBookResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAggregateVoteCountRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetAggregateVoteCountRequest) Reset()         { *m = QueryGetAggregateVoteCountRequest{} }
func (m *QueryGetAggregateVoteCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAggregateVoteCountRequest) ProtoMessage()    {}
func (*QueryGetAggregateVoteCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{6}
}
func (m *QueryGetAggregateVoteCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAggregateVoteCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAggregateVoteCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAggregateVoteCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAggregateVoteCountRequest.Merge(m, src)
}
func (m *QueryGetAggregateVoteCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAggregateVoteCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAggregateVoteCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAggregateVoteCountRequest proto.InternalMessageInfo

func (m *QueryGetAggregateVoteCountRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetAggregateVoteCountResponse struct {
	AggregateVoteCount AggregateVoteCount `protobuf:"bytes,1,opt,name=aggregateVoteCount,proto3" json:"aggregateVoteCount"`
}

func (m *QueryGetAggregateVoteCountResponse) Reset()         { *m = QueryGetAggregateVoteCountResponse{} }
func (m *QueryGetAggregateVoteCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAggregateVoteCountResponse) ProtoMessage()    {}
func (*QueryGetAggregateVoteCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{7}
}
func (m *QueryGetAggregateVoteCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAggregateVoteCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAggregateVoteCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAggregateVoteCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAggregateVoteCountResponse.Merge(m, src)
}
func (m *QueryGetAggregateVoteCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAggregateVoteCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAggregateVoteCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAggregateVoteCountResponse proto.InternalMessageInfo

func (m *QueryGetAggregateVoteCountResponse) GetAggregateVoteCount() AggregateVoteCount {
	if m != nil {
		return m.AggregateVoteCount
	}
	return AggregateVoteCount{}
}

type QueryAllAggregateVoteCountRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAggregateVoteCountRequest) Reset()         { *m = QueryAllAggregateVoteCountRequest{} }
func (m *QueryAllAggregateVoteCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAggregateVoteCountRequest) ProtoMessage()    {}
func (*QueryAllAggregateVoteCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{8}
}
func (m *QueryAllAggregateVoteCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAggregateVoteCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAggregateVoteCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAggregateVoteCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAggregateVoteCountRequest.Merge(m, src)
}
func (m *QueryAllAggregateVoteCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAggregateVoteCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAggregateVoteCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAggregateVoteCountRequest proto.InternalMessageInfo

func (m *QueryAllAggregateVoteCountRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAggregateVoteCountResponse struct {
	AggregateVoteCount []AggregateVoteCount `protobuf:"bytes,1,rep,name=aggregateVoteCount,proto3" json:"aggregateVoteCount"`
	Pagination         *query.PageResponse  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAggregateVoteCountResponse) Reset()         { *m = QueryAllAggregateVoteCountResponse{} }
func (m *QueryAllAggregateVoteCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAggregateVoteCountResponse) ProtoMessage()    {}
func (*QueryAllAggregateVoteCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6328f15707fa237d, []int{9}
}
func (m *QueryAllAggregateVoteCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAggregateVoteCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAggregateVoteCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAggregateVoteCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAggregateVoteCountResponse.Merge(m, src)
}
func (m *QueryAllAggregateVoteCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAggregateVoteCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAggregateVoteCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAggregateVoteCountResponse proto.InternalMessageInfo

func (m *QueryAllAggregateVoteCountResponse) GetAggregateVoteCount() []AggregateVoteCount {
	if m != nil {
		return m.AggregateVoteCount
	}
	return nil
}

func (m *QueryAllAggregateVoteCountResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mande.voting.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mande.voting.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryGetVoteBookRequest)(nil), "mande.voting.v1beta1.QueryGetVoteBookRequest")
	proto.RegisterType((*QueryGetVoteBookResponse)(nil), "mande.voting.v1beta1.QueryGetVoteBookResponse")
	proto.RegisterType((*QueryAllVoteBookRequest)(nil), "mande.voting.v1beta1.QueryAllVoteBookRequest")
	proto.RegisterType((*QueryAllVoteBookResponse)(nil), "mande.voting.v1beta1.QueryAllVoteBookResponse")
	proto.RegisterType((*QueryGetAggregateVoteCountRequest)(nil), "mande.voting.v1beta1.QueryGetAggregateVoteCountRequest")
	proto.RegisterType((*QueryGetAggregateVoteCountResponse)(nil), "mande.voting.v1beta1.QueryGetAggregateVoteCountResponse")
	proto.RegisterType((*QueryAllAggregateVoteCountRequest)(nil), "mande.voting.v1beta1.QueryAllAggregateVoteCountRequest")
	proto.RegisterType((*QueryAllAggregateVoteCountResponse)(nil), "mande.voting.v1beta1.QueryAllAggregateVoteCountResponse")
}

func init() { proto.RegisterFile("mande/voting/v1beta1/query.proto", fileDescriptor_6328f15707fa237d) }

var fileDescriptor_6328f15707fa237d = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xeb, 0x8d, 0x55, 0xc3, 0xbb, 0x99, 0xc2, 0x46, 0x35, 0x65, 0x9b, 0x85, 0xd8, 0xa8,
	0x68, 0xac, 0x96, 0xc3, 0x80, 0x13, 0x2d, 0x12, 0xbd, 0xb2, 0x1e, 0x38, 0x20, 0xc4, 0xe4, 0x74,
	0x96, 0x89, 0x9a, 0xc6, 0x59, 0xe3, 0x56, 0x9b, 0x26, 0x2e, 0x88, 0x2b, 0x12, 0x82, 0x2f, 0xc0,
	0x85, 0xaf, 0xc0, 0x85, 0x2f, 0xb0, 0x0b, 0xd2, 0x24, 0x2e, 0x9c, 0x10, 0x6a, 0xf9, 0x20, 0x28,
	0xb6, 0xd3, 0x11, 0x92, 0xa6, 0x1b, 0xea, 0x6d, 0x73, 0xde, 0xff, 0xbd, 0xdf, 0xff, 0x3d, 0xfb,
	0x15, 0x6e, 0xf6, 0xa8, 0x7f, 0xc0, 0xc8, 0x50, 0x48, 0xd7, 0xe7, 0x64, 0x58, 0x73, 0x98, 0xa4,
	0x35, 0x72, 0x38, 0x60, 0xfd, 0x63, 0x3b, 0xe8, 0x0b, 0x29, 0x50, 0x49, 0x45, 0xd8, 0x3a, 0xc2,
	0x36, 0x11, 0xe5, 0x12, 0x17, 0x5c, 0xa8, 0x00, 0x12, 0xfd, 0xa5, 0x63, 0xcb, 0xeb, 0x5c, 0x08,
	0xee, 0x31, 0x42, 0x03, 0x97, 0x50, 0xdf, 0x17, 0x92, 0x4a, 0x57, 0xf8, 0xa1, 0xf9, 0x5a, 0xe9,
	0x88, 0xb0, 0x27, 0x42, 0xe2, 0xd0, 0x90, 0xe9, 0x12, 0x93, 0x82, 0x01, 0xe5, 0xae, 0xaf, 0x82,
	0x4d, 0xec, 0x56, 0x26, 0x97, 0x81, 0xc8, 0x0b, 0x09, 0x68, 0x9f, 0xf6, 0x4c, 0x45, 0x5c, 0x82,
	0x68, 0x2f, 0xaa, 0xf3, 0x54, 0x1d, 0xb6, 0xd9, 0xe1, 0x80, 0x85, 0x12, 0xef, 0xc1, 0x6b, 0x89,
	0xd3, 0x30, 0x10, 0x7e, 0xc8, 0xd0, 0x43, 0x58, 0xd4, 0xe2, 0x35, 0xb0, 0x09, 0x76, 0x56, 0xea,
	0xeb, 0x76, 0x96, 0x73, 0x5b, 0xab, 0x9a, 0x57, 0x4e, 0x7f, 0x6e, 0x14, 0xda, 0x46, 0x81, 0x09,
	0x5c, 0x55, 0x29, 0x5b, 0x4c, 0x3e, 0x13, 0x92, 0x35, 0x85, 0xe8, 0x9a, 0x6a, 0xa8, 0x04, 0x97,
	0x5c, 0xff, 0x80, 0x1d, 0xa9, 0xac, 0x57, 0xdb, 0xfa, 0x1f, 0xfc, 0x02, 0xae, 0xa5, 0x05, 0x06,
	0xe4, 0x11, 0x5c, 0x1e, 0x9a, 0x33, 0x83, 0x62, 0x65, 0xa3, 0xc4, 0x4a, 0x03, 0x33, 0x51, 0x61,
	0x6a, 0x70, 0x1a, 0x9e, 0xf7, 0x2f, 0xce, 0x13, 0x08, 0xcf, 0x9b, 0x6d, 0xd2, 0xdf, 0xb6, 0xf5,
	0x64, 0xec, 0x68, 0x32, 0xb6, 0x1e, 0xfe, 0xb9, 0x5d, 0xce, 0x8c, 0xb6, 0xfd, 0x97, 0x12, 0x7f,
	0x06, 0xc6, 0x41, 0xa2, 0x46, 0xa6, 0x83, 0xc5, 0xcb, 0x3b, 0x40, 0xad, 0x04, 0xe6, 0x82, 0xc2,
	0xdc, 0x9e, 0x89, 0xa9, 0xcb, 0x27, 0x38, 0x1f, 0xc0, 0xad, 0xb8, 0xd1, 0x0d, 0xce, 0xfb, 0x8c,
	0x53, 0xc9, 0xa2, 0xaa, 0x8f, 0xc5, 0xc0, 0x97, 0xf9, 0x33, 0x7a, 0x0b, 0x20, 0xce, 0xd3, 0x1a,
	0xb3, 0x2f, 0x21, 0xa2, 0xa9, 0xaf, 0xa6, 0xb3, 0x3b, 0xd9, 0xb6, 0xd3, 0xd9, 0x4c, 0x03, 0x32,
	0x32, 0xe1, 0xae, 0x71, 0xd0, 0xf0, 0xbc, 0xe9, 0x0e, 0xe6, 0x35, 0xd6, 0x6f, 0xb1, 0xe7, 0x29,
	0xd5, 0x66, 0x78, 0x5e, 0x9c, 0x8f, 0xe7, 0xb9, 0x8d, 0xbf, 0xfe, 0xa9, 0x08, 0x97, 0x94, 0x1f,
	0x74, 0x02, 0x8b, 0xfa, 0xe9, 0xa2, 0x29, 0x80, 0xe9, 0x4d, 0x51, 0xbe, 0x73, 0x81, 0x48, 0x5d,
	0x14, 0xaf, 0xbf, 0xf9, 0xfe, 0xfb, 0xe3, 0xc2, 0x0d, 0x54, 0x22, 0x89, 0xb5, 0xa4, 0xf7, 0x03,
	0xfa, 0x00, 0xe0, 0x72, 0x7c, 0xd7, 0x51, 0x35, 0x27, 0x6b, 0x7a, 0x81, 0x94, 0xed, 0x8b, 0x86,
	0x1b, 0x92, 0x6d, 0x45, 0xb2, 0x85, 0x36, 0x92, 0x24, 0xd1, 0xd3, 0xda, 0x77, 0x84, 0xe8, 0x92,
	0x13, 0x75, 0xbd, 0x5f, 0xa3, 0x77, 0x00, 0xae, 0xc4, 0xea, 0x86, 0xe7, 0xe5, 0x72, 0xa5, 0x37,
	0x49, 0x2e, 0x57, 0xc6, 0x52, 0xc0, 0x1b, 0x8a, 0xeb, 0x26, 0x5a, 0x9d, 0xc2, 0x85, 0xbe, 0x02,
	0x88, 0xd2, 0xb7, 0x04, 0xed, 0xe6, 0xfb, 0x9f, 0xfa, 0x26, 0xca, 0xf7, 0x2f, 0x2f, 0x34, 0xa8,
	0x75, 0x85, 0x7a, 0x17, 0x55, 0x92, 0xa8, 0x93, 0x8b, 0xba, 0xaf, 0xa0, 0x3b, 0x91, 0x66, 0xd2,
	0xcd, 0x2f, 0x00, 0x5e, 0x4f, 0xa7, 0x8c, 0xfa, 0xba, 0x9b, 0xdf, 0xa8, 0xff, 0x33, 0x90, 0xfb,
	0x3e, 0x71, 0x45, 0x19, 0xb8, 0x85, 0xf0, 0x6c, 0x03, 0xcd, 0xd6, 0xe9, 0xc8, 0x02, 0x67, 0x23,
	0x0b, 0xfc, 0x1a, 0x59, 0xe0, 0xfd, 0xd8, 0x2a, 0x9c, 0x8d, 0xad, 0xc2, 0x8f, 0xb1, 0x55, 0x78,
	0x5e, 0xe5, 0xae, 0x7c, 0x35, 0x70, 0xec, 0x8e, 0xe8, 0xe9, 0x3c, 0x55, 0x8f, 0x3a, 0x61, 0x9c,
	0xb2, 0x46, 0x8e, 0xe2, 0xbc, 0xf2, 0x38, 0x60, 0xa1, 0x53, 0x54, 0x3f, 0xba, 0xf7, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xd3, 0x12, 0x43, 0xda, 0x54, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a VoteBook by index.
	VoteBook(ctx context.Context, in *QueryGetVoteBookRequest, opts ...grpc.CallOption) (*QueryGetVoteBookResponse, error)
	// Queries a list of VoteBook items.
	VoteBookAll(ctx context.Context, in *QueryAllVoteBookRequest, opts ...grpc.CallOption) (*QueryAllVoteBookResponse, error)
	// Queries a AggregateVoteCount by index.
	AggregateVoteCount(ctx context.Context, in *QueryGetAggregateVoteCountRequest, opts ...grpc.CallOption) (*QueryGetAggregateVoteCountResponse, error)
	// Queries a list of AggregateVoteCount items.
	AggregateVoteCountAll(ctx context.Context, in *QueryAllAggregateVoteCountRequest, opts ...grpc.CallOption) (*QueryAllAggregateVoteCountResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mande.voting.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteBook(ctx context.Context, in *QueryGetVoteBookRequest, opts ...grpc.CallOption) (*QueryGetVoteBookResponse, error) {
	out := new(QueryGetVoteBookResponse)
	err := c.cc.Invoke(ctx, "/mande.voting.v1beta1.Query/VoteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteBookAll(ctx context.Context, in *QueryAllVoteBookRequest, opts ...grpc.CallOption) (*QueryAllVoteBookResponse, error) {
	out := new(QueryAllVoteBookResponse)
	err := c.cc.Invoke(ctx, "/mande.voting.v1beta1.Query/VoteBookAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AggregateVoteCount(ctx context.Context, in *QueryGetAggregateVoteCountRequest, opts ...grpc.CallOption) (*QueryGetAggregateVoteCountResponse, error) {
	out := new(QueryGetAggregateVoteCountResponse)
	err := c.cc.Invoke(ctx, "/mande.voting.v1beta1.Query/AggregateVoteCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AggregateVoteCountAll(ctx context.Context, in *QueryAllAggregateVoteCountRequest, opts ...grpc.CallOption) (*QueryAllAggregateVoteCountResponse, error) {
	out := new(QueryAllAggregateVoteCountResponse)
	err := c.cc.Invoke(ctx, "/mande.voting.v1beta1.Query/AggregateVoteCountAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a VoteBook by index.
	VoteBook(context.Context, *QueryGetVoteBookRequest) (*QueryGetVoteBookResponse, error)
	// Queries a list of VoteBook items.
	VoteBookAll(context.Context, *QueryAllVoteBookRequest) (*QueryAllVoteBookResponse, error)
	// Queries a AggregateVoteCount by index.
	AggregateVoteCount(context.Context, *QueryGetAggregateVoteCountRequest) (*QueryGetAggregateVoteCountResponse, error)
	// Queries a list of AggregateVoteCount items.
	AggregateVoteCountAll(context.Context, *QueryAllAggregateVoteCountRequest) (*QueryAllAggregateVoteCountResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) VoteBook(ctx context.Context, req *QueryGetVoteBookRequest) (*QueryGetVoteBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteBook not implemented")
}
func (*UnimplementedQueryServer) VoteBookAll(ctx context.Context, req *QueryAllVoteBookRequest) (*QueryAllVoteBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteBookAll not implemented")
}
func (*UnimplementedQueryServer) AggregateVoteCount(ctx context.Context, req *QueryGetAggregateVoteCountRequest) (*QueryGetAggregateVoteCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateVoteCount not implemented")
}
func (*UnimplementedQueryServer) AggregateVoteCountAll(ctx context.Context, req *QueryAllAggregateVoteCountRequest) (*QueryAllAggregateVoteCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateVoteCountAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mande.voting.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVoteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mande.voting.v1beta1.Query/VoteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteBook(ctx, req.(*QueryGetVoteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteBookAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllVoteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteBookAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mande.voting.v1beta1.Query/VoteBookAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteBookAll(ctx, req.(*QueryAllVoteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AggregateVoteCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAggregateVoteCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AggregateVoteCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mande.voting.v1beta1.Query/AggregateVoteCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AggregateVoteCount(ctx, req.(*QueryGetAggregateVoteCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AggregateVoteCountAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAggregateVoteCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AggregateVoteCountAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mande.voting.v1beta1.Query/AggregateVoteCountAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AggregateVoteCountAll(ctx, req.(*QueryAllAggregateVoteCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mande.voting.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "VoteBook",
			Handler:    _Query_VoteBook_Handler,
		},
		{
			MethodName: "VoteBookAll",
			Handler:    _Query_VoteBookAll_Handler,
		},
		{
			MethodName: "AggregateVoteCount",
			Handler:    _Query_AggregateVoteCount_Handler,
		},
		{
			MethodName: "AggregateVoteCountAll",
			Handler:    _Query_AggregateVoteCountAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mande/voting/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetVoteBookRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVoteBookRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVoteBookRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVoteBookResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVoteBookResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVoteBookResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VoteBook.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllVoteBookRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVoteBookRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVoteBookRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllVoteBookResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVoteBookResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVoteBookResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.VoteBook) > 0 {
		for iNdEx := len(m.VoteBook) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VoteBook[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAggregateVoteCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAggregateVoteCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAggregateVoteCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAggregateVoteCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAggregateVoteCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAggregateVoteCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AggregateVoteCount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAggregateVoteCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAggregateVoteCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAggregateVoteCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAggregateVoteCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAggregateVoteCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAggregateVoteCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AggregateVoteCount) > 0 {
		for iNdEx := len(m.AggregateVoteCount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AggregateVoteCount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetVoteBookRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVoteBookResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VoteBook.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllVoteBookRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllVoteBookResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VoteBook) > 0 {
		for _, e := range m.VoteBook {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAggregateVoteCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAggregateVoteCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AggregateVoteCount.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAggregateVoteCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAggregateVoteCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AggregateVoteCount) > 0 {
		for _, e := range m.AggregateVoteCount {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVoteBookRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVoteBookRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVoteBookRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVoteBookResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVoteBookResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVoteBookResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteBook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteBook.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVoteBookRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVoteBookRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVoteBookRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVoteBookResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVoteBookResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVoteBookResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteBook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteBook = append(m.VoteBook, VoteBook{})
			if err := m.VoteBook[len(m.VoteBook)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAggregateVoteCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAggregateVoteCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAggregateVoteCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAggregateVoteCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAggregateVoteCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAggregateVoteCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregateVoteCount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AggregateVoteCount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAggregateVoteCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAggregateVoteCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAggregateVoteCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAggregateVoteCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAggregateVoteCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAggregateVoteCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregateVoteCount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AggregateVoteCount = append(m.AggregateVoteCount, AggregateVoteCount{})
			if err := m.AggregateVoteCount[len(m.AggregateVoteCount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
